### ISSUE TITLE
Include Jar in the releases

### ISSUE THREAD

**Issue by weihao** [qcastel/github-actions-maven-release-sample#1]
Hi @qcastel,

How to include compiled jar files in the releases?

**Comment by qcastel** [comment]
Hello @weihao ,

Sorry I don't really monitor this repo a lot.

As part of the maven release, you can push jars to an artefactory like nexus. Personally I used Jfrog in the past for that and it was working fine. 
You can see this maven action as a trigger for your release, then you can do the usual maven stuff.
If I got a bit of time one day, I will add this in this sample, to show one way of pushing artefacts as part of the maven release.

If you got more questions, don't hesitate to open a ticket on the other repo https://github.com/qcastel/github-actions-maven-release , I just tends to be more responsive on the other one.
